# Generated by Django 5.1.1 on 2024-11-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_alter_donors_address_alter_donors_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Blood Group')),
                ('organ_needed', models.CharField(max_length=255, verbose_name='Organ Needed')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
