# .github/workflows/test.yml
name: Run Django Tests

# This workflow runs on push to the 'main' branch or when a pull request is made to 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in this workflow
jobs:
  test:
    runs-on: ubuntu-latest  # The OS to use for the job (can be 'ubuntu-latest', 'windows-latest', 'macos-latest')

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Choose the Python version for your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt with dependencies listed

      # Step 4: Run tests
      - name: Run Django tests
        run: |
          python manage.py test notification  # Run the Django tests for the 'notification' app
